version: 0.2
phases:
  pre_build:
    commands:
      - echo pre build started installing requirements
      - python3 -m pip install --upgrade pip
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo build stage started
  post_build:
    commands:
      - echo building  competed on -`date`
artifacts:
  files:
    - '**/*'