# Generated by Django 2.2 on 2024-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_management', '0002_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
