# Generated by Django 2.2 on 2024-10-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_management', '0003_warranty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/products/'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='document_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='warranty_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/warranties/'),
        ),
    ]
