# Generated by Django 2.2 on 2024-10-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('warranty_management', '0004_auto_20241027_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('date_of_claim', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10)),
                ('repair_document', models.FileField(blank=True, null=True, upload_to='documents/cliams/')),
                ('document_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('resolution_description', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='customer.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warranty_management.Product')),
            ],
        ),
    ]
