# Generated by Django 2.2 on 2024-11-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_management', '0005_auto_20241029_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExtendedWarranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('warranty_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('warranty_period', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warranty_management.Warranty')),
            ],
        ),
    ]
