# Generated by Django 2.2 on 2024-11-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_management', '0006_auto_20241101_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='issue_severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low')], default='MODERATE', max_length=10),
        ),
    ]
