# Generated by Django 2.2 on 2024-11-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('warranty_management', '0007_claim_issue_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedwarranty',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extended_warranties', to='customer.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
