# Generated by Django 2.2 on 2024-11-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_management', '0008_auto_20241107_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedwarranty',
            name='amount_claimed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
